name: tests

on: [push]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    name: unit tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: python test_choc_an.py
